// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SqlPlastic.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DefaultConfig")]
    public partial class DefaultConfigFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DefaultConfig.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DefaultConfig", "\tModel building with the default options and mapping rules", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify all datatypes are mapped correctly by default")]
        public virtual void VerifyAllDatatypesAreMappedCorrectlyByDefault()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify all datatypes are mapped correctly by default", ((string[])(null)));
#line 4
 this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Column Name",
                        "Member Type"});
            table1.AddRow(new string[] {
                        "MyDataTypeID",
                        "int"});
            table1.AddRow(new string[] {
                        "MyBool",
                        "bool"});
            table1.AddRow(new string[] {
                        "MyTinyInt",
                        "byte"});
            table1.AddRow(new string[] {
                        "MyInt",
                        "int"});
            table1.AddRow(new string[] {
                        "MyBigInt",
                        "long"});
            table1.AddRow(new string[] {
                        "MySmallMoney",
                        "decimal"});
            table1.AddRow(new string[] {
                        "MyMoney",
                        "decimal"});
            table1.AddRow(new string[] {
                        "MyDecimal",
                        "decimal"});
            table1.AddRow(new string[] {
                        "MyNumeric",
                        "decimal"});
            table1.AddRow(new string[] {
                        "MyReal",
                        "float"});
            table1.AddRow(new string[] {
                        "MyFloat",
                        "double"});
            table1.AddRow(new string[] {
                        "MyChar1",
                        "char"});
            table1.AddRow(new string[] {
                        "MyChar10",
                        "string"});
            table1.AddRow(new string[] {
                        "MyVarChar100",
                        "string"});
            table1.AddRow(new string[] {
                        "MyVarCharMax",
                        "string"});
            table1.AddRow(new string[] {
                        "MyNVarChar100",
                        "string"});
            table1.AddRow(new string[] {
                        "MyText",
                        "string"});
            table1.AddRow(new string[] {
                        "MyXML",
                        "System.Xml.Linq.XElement"});
            table1.AddRow(new string[] {
                        "MySmallDateTime",
                        "System.DateTime"});
            table1.AddRow(new string[] {
                        "MyDateTime",
                        "System.DateTime"});
            table1.AddRow(new string[] {
                        "MyDateTime2",
                        "System.DateTime"});
            table1.AddRow(new string[] {
                        "MyDateTimeOffset",
                        "System.DateTimeOffset"});
            table1.AddRow(new string[] {
                        "MyDate",
                        "System.DateTime"});
            table1.AddRow(new string[] {
                        "MyTime",
                        "System.Timespan"});
            table1.AddRow(new string[] {
                        "MyBinary50",
                        "System.Data.Linq.Binary"});
            table1.AddRow(new string[] {
                        "MyVarBinary60",
                        "System.Data.Linq.Binary"});
            table1.AddRow(new string[] {
                        "MyVarBinaryMax",
                        "System.Data.Linq.Binary"});
            table1.AddRow(new string[] {
                        "MyTimeStamp",
                        "System.Data.Linq.Binary"});
            table1.AddRow(new string[] {
                        "MyGUID",
                        "System.GUID"});
#line 7
 testRunner.Then("the resulting table \"MyDataTypes\" should contain exactly the following columns", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("All tables, columns, and keys should be present")]
        public virtual void AllTablesColumnsAndKeysShouldBePresent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All tables, columns, and keys should be present", ((string[])(null)));
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 41
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "TableName",
                        "Columns",
                        "EntityRefs",
                        "EntitySets"});
            table2.AddRow(new string[] {
                        "Customers",
                        "3",
                        "1",
                        "4"});
            table2.AddRow(new string[] {
                        "CustomerPhotos",
                        "2",
                        "1",
                        "0"});
            table2.AddRow(new string[] {
                        "Products",
                        "3",
                        "0",
                        "1"});
            table2.AddRow(new string[] {
                        "Orders",
                        "3",
                        "1",
                        "1"});
            table2.AddRow(new string[] {
                        "OrderLineItems",
                        "4",
                        "2",
                        "0"});
            table2.AddRow(new string[] {
                        "Employees",
                        "4",
                        "1",
                        "1"});
            table2.AddRow(new string[] {
                        "Preferences",
                        "4",
                        "3",
                        "0"});
            table2.AddRow(new string[] {
                        "MyDataTypes",
                        "29",
                        "0",
                        "0"});
#line 42
 testRunner.Then("the resulting model should contain the following tables", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Entity Refs 1 - Self reference should end in a 1 by default")]
        public virtual void EntityRefs1_SelfReferenceShouldEndInA1ByDefault()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Entity Refs 1 - Self reference should end in a 1 by default", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 56
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityRefName",
                        "KeyColumn",
                        "ReferencedColumn",
                        "AssociatedSet",
                        "ForeignKeyName",
                        "DeleteRule",
                        "DeleteOnNull"});
            table3.AddRow(new string[] {
                        "Employee1",
                        "ManagerEmployeeID",
                        "EmployeeID",
                        "Employees",
                        "FK_ManagerID",
                        "NO_ACTION",
                        "false"});
#line 57
 testRunner.Then("the table \"Employees\" should contain the following entity references", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Entity Refs 2")]
        public virtual void EntityRefs2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Entity Refs 2", ((string[])(null)));
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityRefName",
                        "KeyColumn",
                        "ReferencedColumn",
                        "AssociatedSet",
                        "ForeignKeyName",
                        "DeleteRule",
                        "DeleteOnNull"});
            table4.AddRow(new string[] {
                        "Order",
                        "LineOrderID",
                        "OrderID",
                        "OrderLineItems",
                        "FK_Orders",
                        "CASCADE",
                        "true"});
            table4.AddRow(new string[] {
                        "Product",
                        "LineProductID",
                        "ProductID",
                        "OrderLineItems",
                        "FK_Products",
                        "CASCADE",
                        "true"});
#line 64
 testRunner.Then("the table \"OrderLineItems\" should contain the following entity references", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Entity Refs 3 - One-to-One relationship")]
        public virtual void EntityRefs3_One_To_OneRelationship()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Entity Refs 3 - One-to-One relationship", ((string[])(null)));
#line 69
this.ScenarioSetup(scenarioInfo);
#line 70
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 71
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityRefName",
                        "KeyColumn",
                        "ReferencedColumn",
                        "AssociatedSet",
                        "ForeignKeyName",
                        "DeleteRule",
                        "DeleteOnNull"});
            table5.AddRow(new string[] {
                        "CustomerPhoto",
                        "CustomerID",
                        "CustomerID",
                        "---",
                        "FK_CustomerPhotos",
                        "CASCADE",
                        "true"});
#line 72
 testRunner.Then("the table \"Customers\" should contain the following entity references", ((string)(null)), table5, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityRefName",
                        "KeyColumn",
                        "ReferencedColumn",
                        "AssociatedSet",
                        "ForeignKeyName",
                        "DeleteRule",
                        "DeleteOnNull"});
#line 75
 testRunner.And("the table \"CustomerPhotos\" should contain the following entity references", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Entity Sets 1")]
        public virtual void EntitySets1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Entity Sets 1", ((string[])(null)));
#line 80
this.ScenarioSetup(scenarioInfo);
#line 81
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 82
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntitySetName",
                        "KeyColumn",
                        "ReferencedColumn",
                        "AssociatedRef",
                        "ForeignKeyName",
                        "DeleteRule"});
            table7.AddRow(new string[] {
                        "Orders",
                        "CustomerID",
                        "OrderCustomerID",
                        "Customer",
                        "FK_Customers",
                        "CASCADE"});
            table7.AddRow(new string[] {
                        "Preferences",
                        "CustomerID",
                        "CustomerID_A",
                        "Customer",
                        "FK_CustomerID_A",
                        "NO_ACTION"});
            table7.AddRow(new string[] {
                        "Preferences1",
                        "CustomerID",
                        "CustomerID_B",
                        "Customer1",
                        "FK_CustomerID_B",
                        "NO_ACTION"});
            table7.AddRow(new string[] {
                        "Preferences2",
                        "CustomerID",
                        "CustomerID_C",
                        "Customer2",
                        "FK_CustomerID_C",
                        "NO_ACTION"});
#line 83
 testRunner.Then("the table \"Customers\" should contain the following entity sets", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Column Attributes 1 - Primary Key with Identity")]
        public virtual void ColumnAttributes1_PrimaryKeyWithIdentity()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Column Attributes 1 - Primary Key with Identity", ((string[])(null)));
#line 90
this.ScenarioSetup(scenarioInfo);
#line 91
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 92
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "AttributeName",
                        "AttributeValue"});
            table8.AddRow(new string[] {
                        "Storage",
                        "\"_CustomerID\""});
            table8.AddRow(new string[] {
                        "AutoSync",
                        "AutoSync.OnInsert"});
            table8.AddRow(new string[] {
                        "DbType",
                        "\"Int NOT NULL IDENTITY\""});
            table8.AddRow(new string[] {
                        "IsPrimaryKey",
                        "true"});
            table8.AddRow(new string[] {
                        "IsDbGenerated",
                        "true"});
#line 93
 testRunner.Then("the column \"dbo.Customers.CustomerID\" should have the following Column Attributes" +
                    "", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Column Attributes 2 - Primary Key no Identity, table has TIMESTAMP")]
        public virtual void ColumnAttributes2_PrimaryKeyNoIdentityTableHasTIMESTAMP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Column Attributes 2 - Primary Key no Identity, table has TIMESTAMP", ((string[])(null)));
#line 101
this.ScenarioSetup(scenarioInfo);
#line 102
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 103
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "AttributeName",
                        "AttributeValue"});
            table9.AddRow(new string[] {
                        "Storage",
                        "\"_MyDataTypeID\""});
            table9.AddRow(new string[] {
                        "DbType",
                        "\"Int NOT NULL\""});
            table9.AddRow(new string[] {
                        "IsPrimaryKey",
                        "true"});
            table9.AddRow(new string[] {
                        "UpdateCheck",
                        "UpdateCheck.Never"});
#line 104
 testRunner.Then("the column \"dbo.MyDataTypes.MyDataTypeID\" should have the following Column Attrib" +
                    "utes", ((string)(null)), table9, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Column Attributes 3 - TimeStamp")]
        public virtual void ColumnAttributes3_TimeStamp()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Column Attributes 3 - TimeStamp", ((string[])(null)));
#line 111
this.ScenarioSetup(scenarioInfo);
#line 112
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 113
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "AttributeName",
                        "AttributeValue"});
            table10.AddRow(new string[] {
                        "Storage",
                        "\"_MyTimeStamp\""});
            table10.AddRow(new string[] {
                        "AutoSync",
                        "AutoSync.Always"});
            table10.AddRow(new string[] {
                        "DbType",
                        "\"rowversion NOT NULL\""});
            table10.AddRow(new string[] {
                        "CanBeNull",
                        "false"});
            table10.AddRow(new string[] {
                        "IsDbGenerated",
                        "true"});
            table10.AddRow(new string[] {
                        "IsVersion",
                        "true"});
            table10.AddRow(new string[] {
                        "UpdateCheck",
                        "UpdateCheck.Never"});
#line 114
 testRunner.Then("the column \"dbo.MyDataTypes.MyTimeStamp\" should have the following Column Attribu" +
                    "tes", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Column Attributes 4 - Nullable int column")]
        public virtual void ColumnAttributes4_NullableIntColumn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Column Attributes 4 - Nullable int column", ((string[])(null)));
#line 124
this.ScenarioSetup(scenarioInfo);
#line 125
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 126
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "AttributeName",
                        "AttributeValue"});
            table11.AddRow(new string[] {
                        "Storage",
                        "\"_ManagerEmployeeID\""});
            table11.AddRow(new string[] {
                        "DbType",
                        "\"Int\""});
#line 127
 testRunner.Then("the column \"dbo.Employees.ManagerEmployeeID\" should have the following Column Att" +
                    "ributes", ((string)(null)), table11, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Column Attributes 5 - Nullable VARCHAR")]
        public virtual void ColumnAttributes5_NullableVARCHAR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Column Attributes 5 - Nullable VARCHAR", ((string[])(null)));
#line 132
this.ScenarioSetup(scenarioInfo);
#line 133
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 134
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "AttributeName",
                        "AttributeValue"});
            table12.AddRow(new string[] {
                        "Storage",
                        "\"_EmployeeTitle\""});
            table12.AddRow(new string[] {
                        "DbType",
                        "\"VarChar(200)\""});
            table12.AddRow(new string[] {
                        "CanBeNull",
                        "true"});
#line 135
 testRunner.Then("the column \"dbo.Employees.EmployeeTitle\" should have the following Column Attribu" +
                    "tes", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Column Attributes 6 - NonNullable VARCHAR")]
        public virtual void ColumnAttributes6_NonNullableVARCHAR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Column Attributes 6 - NonNullable VARCHAR", ((string[])(null)));
#line 141
this.ScenarioSetup(scenarioInfo);
#line 142
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 143
 testRunner.When("I generate models with the default options", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "AttributeName",
                        "AttributeValue"});
            table13.AddRow(new string[] {
                        "Storage",
                        "\"_EmployeeName\""});
            table13.AddRow(new string[] {
                        "DbType",
                        "\"VarChar(100) NOT NULL\""});
            table13.AddRow(new string[] {
                        "CanBeNull",
                        "false"});
#line 144
 testRunner.Then("the column \"dbo.Employees.EmployeeName\" should have the following Column Attribut" +
                    "es", ((string)(null)), table13, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MaxLength Attributes 1")]
        public virtual void MaxLengthAttributes1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MaxLength Attributes 1", ((string[])(null)));
#line 151
this.ScenarioSetup(scenarioInfo);
#line 152
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table14.AddRow(new string[] {
                        "MaxLengthAttributes",
                        "true"});
#line 153
 testRunner.When("I generate models with the following options", ((string)(null)), table14, "When ");
#line 156
 testRunner.Then("the column \"dbo.Employees.EmployeeName\" should have a MaxLengthAttribute of \"100\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MaxLength Attributes 2")]
        public virtual void MaxLengthAttributes2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MaxLength Attributes 2", ((string[])(null)));
#line 158
this.ScenarioSetup(scenarioInfo);
#line 159
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table15.AddRow(new string[] {
                        "MaxLengthAttributes",
                        "false"});
#line 160
 testRunner.When("I generate models with the following options", ((string)(null)), table15, "When ");
#line 163
 testRunner.Then("the column \"dbo.Employees.EmployeeName\" should have a MaxLengthAttribute of \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MaxLength Attributes 3")]
        public virtual void MaxLengthAttributes3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MaxLength Attributes 3", ((string[])(null)));
#line 165
this.ScenarioSetup(scenarioInfo);
#line 166
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table16.AddRow(new string[] {
                        "MaxLengthAttributes",
                        "true"});
#line 167
 testRunner.When("I generate models with the following options", ((string)(null)), table16, "When ");
#line 170
 testRunner.Then("the column \"dbo.MyDataTypes.MyChar1\" should have a MaxLengthAttribute of \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("MaxLength Attributes 4 - Timestamp columns should not have maxlength")]
        public virtual void MaxLengthAttributes4_TimestampColumnsShouldNotHaveMaxlength()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MaxLength Attributes 4 - Timestamp columns should not have maxlength", ((string[])(null)));
#line 172
this.ScenarioSetup(scenarioInfo);
#line 173
 testRunner.Given("a connection to the \"SqlPlasticTestDB\" database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table17.AddRow(new string[] {
                        "MaxLengthAttributes",
                        "true"});
#line 174
 testRunner.When("I generate models with the following options", ((string)(null)), table17, "When ");
#line 177
 testRunner.Then("the column \"dbo.MyDataTypes.MyVarChar100\" should have a MaxLengthAttribute of \"10" +
                    "0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 178
 testRunner.And("the column \"dbo.MyDataTypes.MyTimeStamp\" should have a MaxLengthAttribute of \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
